global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80/tcp
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
    #       scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: le
  traefik:
    address: :57127/tcp

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
  docker:
    watch: true
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
 
 api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: youur@email.ru
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
http:
  middlewares:
    limit:
      rateLimit:
        average: 200
        period: 1m
    flight:
      inFlightReq:
        amount: 200
